"use strict";
exports.__esModule = true;
var claseCliente_1 = require("./claseCliente");
var claseRevista_1 = require("./claseRevista");
var claseLibro_1 = require("./claseLibro");
var claseLibreria_1 = require("./claseLibreria");
var autores = ['Pedro', 'Rosa', 'Fabian'];
var generos = ['Drama', 'Terror', 'Comedia', 'Vaqueros'];
var cliente1 = new claseCliente_1.Cliente('Juan', 'Perez', 111, 'ASDAS', autores, generos, 0.1);
var cliente2 = new claseCliente_1.Cliente('Javer', 'Paez', 222, 'Nuñez', autores, generos, 0.3);
var libro1 = new claseLibro_1.Libro('Titulo1', 140, 'Pedro', 2100, 'Comedia', 'asdasdas');
var libro2 = new claseLibro_1.Libro('Titulo2', 340, 'Rosa', 500, 'Drama', 'asdasdas');
var revista1 = new claseRevista_1.Revista('Para ti', 20, 'Rosa', 20, 5, 2022);
var revista2 = new claseRevista_1.Revista('Oeste', 10, 'Araceli', 10, 3, 2012);
var arregloCliente = [cliente1, cliente2];
var arregloRevistas = [revista1, revista2];
var arregloLibro = [libro1, libro2];
var libreria1 = new claseLibreria_1.Libreria(arregloCliente, arregloLibro, arregloRevistas);
var primerPrecio = libreria1.calcularPrecio(cliente1, revista1);
console.log(primerPrecio);
var buscar1 = libreria1.buscarRevista(revista1);
console.log(buscar1);
var busca2 = libreria1.buscarLibro(libro2);
console.log(busca2);
cliente1.compraLibro(libro2);
cliente2.compraRevista(revista1);
cliente1.GustoLibro(libro2);
cliente1.GustoLibro(libro1);
console.log(cliente1);
cliente2.GustoLibroExigente(libro1);
console.log(cliente2);
